version: '3.3'

services:
  nut_api:
    image: node:14
    container_name: nut_api
    working_dir: /app
    ports:
      - '4001:4001'
    volumes:
      - .:/app
    depends_on:
      - nut_db
    command: bash -c "npm install && npm run start"

  nut_db:
    image: postgres
    environment:
      POSTGRES_USER: wvecavluwpdvqc
      POSTGRES_PASSWORD: 5562b4625fbca0d044b389fefc865d00d3aa89fe04c9c2d73195ac79e5efd4ba
    volumes:
      - nut_db:/var/lib/postgresql/data
    container_name: nut_db
    
volumes:
  nut_db:
